apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-targets
  namespace: monitoring
  labels:
    prometheus: blackbox
data:
  blackbox-targets.yaml: |
    - job_name: "blackbox-http"
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - http://login-app-frontend.default.svc.cluster.local:3000
          - http://login-app-backend.default.svc.cluster.local:5000
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

